# Generated by Django 4.2.6 on 2023-10-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='pseudoBlog', max_length=255),
        ),
    ]
